name: main
on: push
jobs:
    globaltask:
      runs-on: ubuntu-latest
      steps:
        - name: clone
          uses: actions/checkout@v2
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        - name: install
          run: make setup
        - name: tests
          run: make test
        - name: lint
          run: make lint



